package ca.craigthomas.yacoco3e.components;

public enum DiskCommand
{
    NONE, READ_ADDRESS, READ_SECTOR, READ_MULTIPLE_SECTORS, READ_TRACK,
    WRITE_SECTOR, WRITE_MULTIPLE_SECTORS, WRITE_TRACK, LOAD_VIRTUAL_DISK
}
